### ISSUE TITLE
Crash while trying to add widget

### ISSUE THREAD

**Issue by jfishbone311** [rgocal/Sapphyx_Issue_Tracker#19] opened 2017-05-26 02:15 UTC
Build version: 1.00.03 
Build date: 1979-11-30 00:00:00 
Current date: 2017-05-25 22:14:20 
Device: Huawei Nexus 6P 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
	at com.gsd.launcher.launcher3.BubbleTextView.applyIconAndLabel(BubbleTextView.java:264)
	at com.gsd.launcher.launcher3.BubbleTextView.applyFromPackageItemInfo(BubbleTextView.java:197)
	at com.gsd.launcher.launcher3.widget.WidgetsListAdapter.onBindViewHolder(WidgetsListAdapter.java:122)
	at com.gsd.launcher.launcher3.widget.WidgetsListAdapter.onBindViewHolder(WidgetsListAdapter.java:47)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.gsd.launcher.launcher3.widget.WidgetsContainerView.onLayout(WidgetsContainerView.java:101)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.gsd.launcher.launcher3.dragndrop.DragLayer.onLayout(DragLayer.java:631)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at com.gsd.launcher.sapphyx.view.LauncherDrawerLayout.onLayout(LauncherDrawerLayout.java:750)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6171)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

-

Device info:
---
<table>
<tr><td>App version</td><td>1.00.03</td></tr>
<tr><td>App version code</td><td>4</td></tr>
<tr><td>Android build version</td><td>eng.calpho.20170523.215854</td></tr>
<tr><td>Android release version</td><td>7.1.2</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>N2G47O</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>Beta</td><td>All content, preferences, settings are subject to change.</td></tr>
<tr><td>Private Builds</td><td>true</td></tr>
</table>

**Comment by rgocal** [comment] 2017-05-26 17:01
Should be fixed in next update. Caused by the launcher icon database not identifying the current icon pack in use causeing the widget holder to not be able the draw current icon for each header of widgets available. 

I will keep this open untill confirmed fixed

**Closed as completed** 2017-10-07 15:43 UTC
Labels: bug
